# Generated by Django 5.0 on 2023-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AddField(
            model_name="airport",
            name="short_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
