# Generated by Django 5.0 on 2023-12-21 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0003_alter_flight_options_airport_short_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["flight__departure_time", "row", "seat"]},
        ),
    ]
