# Generated by Django 5.0 on 2023-12-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0004_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"),
                name="unique_set_row",
                violation_error_message="Seat with entered data has been already ordered",
            ),
        ),
    ]
