# Generated by Django 5.0 on 2023-12-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0006_alter_airplane_name_alter_airplanetype_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_set_row",
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"),
                name="validate_unique",
                violation_error_message="some_error",
            ),
        ),
    ]
