# Generated by Django 5.0 on 2023-12-26 19:21

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_remove_ticket_unique_set_row_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="validate_unique",
        ),
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.movie_image_file_path
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"), name="validate_unique"
            ),
        ),
    ]
